---
# adapted from ansible role geerlingguy.dotfiles
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Ensure all configured dotfiles are processed
  block:
    - name: Handle shellscript type files (insert content for .zshrc)
      copy:
        dest: "{{ dotfiles_home }}/{{ item.dest }}"
        content: "source {{ dotfiles_repo_local_destination }}/{{ item.src }}"
        mode: '0644'
      when: item.type == 'shellscript'
      loop: "{{ dotfiles_files }}"
      loop_control:
        label: "{{ item.dest }}"
      become: false

    - name: Handle symbolic links for other files
      file:
        src: "{{ dotfiles_repo_local_destination }}/{{ item.src }}"
        dest: "{{ dotfiles_home }}/{{ item.dest }}"
        state: link
      when: item.type != 'shellscript'
      loop: "{{ dotfiles_files }}"
      loop_control:
        label: "{{ item.dest }}"

    - name: Ensure parent directories of link dotfiles exist.
      file:
        path: "{{ (dotfiles_home ~ '/' ~ item.dest) | dirname }}"
        state: directory
        follow: true
      become: false
      loop: "{{ dotfiles_files }}"
      loop_control:
        label: "{{ item.dest }}"

