---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Set Screensaver moduleName to flurry
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: moduleName
    value: 'flurry'
    state: present
    global: true
    when: configure_osx

- name: Set Screensaver path to /System/Library/Screen Savers/Flurry.saver
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: path
    value: '/System/Library/Screen Savers/Flurry.saver'
    state: present
    global: true
    user: "{{ ansible_user_id }}"
    when: configure_osx

- name: Set Screensaver type to 0
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: moduleDict
    value: '<dict><key>type</key><integer>0</integer></dict>'
    state: present
    global: true
    user: "{{ ansible_user_id }}"
    when: configure_osx

- name: Set Screensaver enabled to true
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: moduleDict
    value: '<dict><key>enabled</key><true/></dict>'
    state: present
    global: true
    user: "{{ ansible_user_id }}"
    when: configure_osx